# ai-trackdown Configuration Example
version: 1

project:
  name: "Sample E-commerce Platform"
  id_prefix: "SHOP"
  description: "Next-generation e-commerce platform with AI-powered recommendations"
  default_epic_budget: 75000
  
formats:
  date: "YYYY-MM-DDTHH:mm:ssZ"
  id_pattern: "{type}-{number:03d}"
  
sync:
  github:
    enabled: true
    repo: "company/ecommerce-platform"
    auth_method: "token"
    branch_patterns: ["feature/{id}-*", "bugfix/{id}-*"]
    
  jira:
    enabled: false
    url: "https://company.atlassian.net"
    project: "SHOP"
    
  linear:
    enabled: false
    team_id: "ecommerce-team"
    
ai:
  llms_txt:
    auto_generate: true
    include_closed: false
    context_depth: 2
    update_frequency: "on_change"
    
  token_tracking:
    enabled: true
    require_agent_id: true
    cost_alerts: true
    daily_budget: 5000
    weekly_budget: 25000
    
  agents:
    claude:
      max_tokens_per_task: 3000
      allowed_operations: ["read", "comment", "update", "analyze"]
      cost_per_1k_input: 0.003
      cost_per_1k_output: 0.015
      
    gpt4:
      max_tokens_per_task: 2000
      allowed_operations: ["read", "comment"]
      cost_per_1k_input: 0.01
      cost_per_1k_output: 0.03
      
    copilot:
      max_tokens_per_task: 1000
      allowed_operations: ["read"]
      cost_per_1k: 0.002
    
git:
  hooks:
    auto_install: true
    commit_parsing: true
    branch_protection: false
    auto_status_update: true
    
  branch_naming:
    enforce: true
    patterns:
      - "feature/{type}-{id}-{slug}"
      - "bugfix/{type}-{id}-{slug}"
      - "epic/{type}-{id}-{slug}"
      
workflow:
  status_transitions:
    todo: ["in-progress", "blocked", "cancelled"]
    in-progress: ["blocked", "in-review", "done", "cancelled"]
    blocked: ["todo", "in-progress", "cancelled"]
    in-review: ["in-progress", "done", "cancelled"]
    done: []
    cancelled: ["todo"]
    
  auto_assignment:
    enabled: true
    round_robin: ["@alice", "@bob", "@charlie"]
    
notifications:
  slack:
    enabled: false
    webhook_url: ""
    channels:
      general: "#team-general"
      critical: "#team-alerts"
      
  email:
    enabled: false
    smtp_server: ""
    
reporting:
  weekly_summary: true
  token_alerts: true
  burndown_charts: true
  velocity_tracking: true