version: 1
project:
  name: "ShopFlow E-commerce Platform Enhancement"
  id_prefix: "SHOP"
  default_epic_budget: 50000
  
formats:
  date: "YYYY-MM-DDTHH:mm:ssZ"
  id_pattern: "{type}-{number:03d}"
  
sync:
  github:
    enabled: true
    repo: "shopflow/platform-enhancement"
    auth_method: "token"
    labels:
      epic: ["epic", "large-feature"]
      issue: ["enhancement", "feature"]
      task: ["task", "subtask"]
    
  jira:
    enabled: true
    url: "https://shopflow.atlassian.net"
    project: "PLATFORM"
    auth_method: "oauth2"
    custom_fields:
      epic_budget: "customfield_10001"
      token_usage: "customfield_10002"
    
  linear:
    enabled: true
    team_id: "platform-team"
    auto_create_cycles: true
    
ai:
  llms_txt:
    auto_generate: true
    include_closed: false
    context_depth: 3
    max_file_size: 100000
    
  token_tracking:
    enabled: true
    require_agent_id: true
    cost_alerts: true
    providers:
      - name: claude-3.5-sonnet
        cost_per_1k_input: 0.003
        cost_per_1k_output: 0.015
      - name: gpt-4-turbo  
        cost_per_1k_input: 0.01
        cost_per_1k_output: 0.03
      - name: github-copilot
        cost_per_1k_input: 0.0001
        cost_per_1k_output: 0.0001
    
  agents:
    claude:
      max_tokens_per_task: 5000
      allowed_operations: ["read", "comment", "update", "analyze"]
      cost_limit_daily: 50
    
    gpt4:
      max_tokens_per_task: 3000
      allowed_operations: ["read", "comment", "review"]
      cost_limit_daily: 30
      
    copilot:
      max_tokens_per_task: 1000
      allowed_operations: ["read", "suggest"]
      cost_limit_daily: 10
    
git:
  hooks:
    auto_install: true
    commit_parsing: true
    branch_protection: true
  
  branch_naming:
    pattern: "{type}/{id}-{slug}"
    types: ["feature", "bugfix", "epic", "hotfix"]
    
notifications:
  slack:
    enabled: true
    webhook_url: "${SLACK_WEBHOOK_URL}"
    channels:
      epic_updates: "#platform-epics"
      daily_standup: "#platform-standup"
      token_alerts: "#ai-costs"
      
  email:
    enabled: false
    
reporting:
  weekly_summary: true
  token_threshold_alerts: true
  burndown_tracking: true
  
security:
  audit_trail: true
  ai_actions_require_approval: false
  sensitive_data_patterns:
    - "password"
    - "secret" 
    - "token"
    - "api_key"