# Minimal ai-trackdown Configuration
# Perfect for individual developers or small teams getting started

version: 1
project:
  name: "My Project"
  id_prefix: "PROJ"

# Basic AI token tracking
ai:
  token_tracking:
    enabled: true
    providers:
      claude:
        model: "claude-3.5-sonnet"
        cost_per_1k_input: 0.003
        cost_per_1k_output: 0.015

# Auto-generate llms.txt for AI context
ai:
  llms_txt:
    auto_generate: true
    update_frequency: "on_change"

# Basic git integration
git:
  hooks:
    auto_install: true
    commit_parsing: true