# Minimal AI Trackdown Configuration Template
# Perfect for individual developers or small teams getting started
# Copy this template to your AI-TRACKDOWN.md file and customize

version: 1
project:
  name: "My Project"
  id_prefix: "PROJ"

# Manual AI token tracking configuration
ai:
  token_tracking:
    manual_tracking: true
    providers:
      claude:
        model: "claude-3.5-sonnet"
        cost_per_1k_input: 0.003
        cost_per_1k_output: 0.015

# Manual llms.txt management
ai:
  llms_txt:
    location: "docs/llms.txt"
    update_workflow: "manual_update_after_task_changes"

# Git workflow integration
git:
  commit_conventions:
    task_references: true
    token_usage_in_commits: true